# Generated by Django 6.0 on 2026-03-16 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('industry_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FinalOutcome',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.student')),
                ('graduating_cpi', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_credits_earned', models.PositiveIntegerField()),
                ('class_awarded', models.CharField(max_length=50)),
                ('degree_awarded', models.CharField(max_length=255)),
                ('graduation_year', models.PositiveSmallIntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['student'], name='final_outcome_student_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlacementOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255)),
                ('package_ctc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_type', models.CharField(max_length=50)),
                ('min_cpi', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('max_backlogs', models.PositiveSmallIntegerField(default=0)),
                ('application_deadline', models.DateTimeField()),
                ('allowed_programs', models.ManyToManyField(blank=True, to='academics.program')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placements.company')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Offered', 'Offered'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('placement_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placements.placementoffer')),
            ],
        ),
        migrations.AddIndex(
            model_name='placementoffer',
            index=models.Index(fields=['company'], name='placement_offer_company_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['student'], name='application_student_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['placement_offer'], name='application_offer_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student', 'placement_offer')},
        ),
    ]
