# Generated by Django 6.0 on 2026-04-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementoffer',
            name='max_semester',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='placementoffer',
            name='min_semester',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='placementoffer',
            name='offer_type',
            field=models.CharField(blank=True, choices=[('JOB', 'Job'), ('INTERNSHIP', 'Internship'), ('PPO', 'PPO')], max_length=50, null=True),
        ),
    ]
