# Generated by Django 6.0 on 2026-04-14 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=200)),
                ('credits', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('HS', 'Humanities'), ('MS', 'Maths'), ('SC', 'Science'), ('PC', 'Program Core'), ('PE', 'Program Elective'), ('OE', 'Open Elective')], max_length=10)),
                ('min_attendance_req', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('grade_letter', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('grade_point', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'grade_scale',
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('offering_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=20)),
                ('semester_no', models.PositiveSmallIntegerField()),
                ('max_capacity', models.PositiveIntegerField(default=60)),
                ('is_grading_finalized', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
            ],
            options={
                'db_table': 'course_offering',
            },
        ),
        migrations.CreateModel(
            name='AssessmentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MIDSEM', 'Midsem'), ('ENDSEM', 'Endsem'), ('QUIZ', 'Quiz'), ('PROJECT', 'Project'), ('LAB', 'Lab'), ('ASSIGNMENT', 'Assignment')], max_length=50)),
                ('weightage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.courseoffering')),
            ],
            options={
                'db_table': 'assessment_component',
                'unique_together': {('offering', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('attempt_no', models.PositiveSmallIntegerField()),
                ('enrollment_type', models.CharField(max_length=50)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.faculty')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.courseoffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
            options={
                'db_table': 'enrollment',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.enrollment')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='CourseGradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.courseoffering')),
                ('grade_letter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.gradescale')),
            ],
            options={
                'db_table': 'course_grade_scale',
            },
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_grade_req', models.CharField(max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='academics.course')),
                ('prereq_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='academics.course')),
            ],
            options={
                'db_table': 'prerequisite',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('duration_years', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'program',
                'unique_together': {('degree', 'branch')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.program'),
        ),
        migrations.CreateModel(
            name='RegistrationWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_no', models.PositiveSmallIntegerField()),
                ('academic_year', models.CharField(max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'registration_window',
                'constraints': [models.UniqueConstraint(fields=('semester_no', 'academic_year'), name='unique_registration_window')],
            },
        ),
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('semester_no', models.PositiveSmallIntegerField()),
                ('spi', models.DecimalField(decimal_places=2, max_digits=4)),
                ('credits_earned_sem', models.PositiveSmallIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
            options={
                'db_table': 'semester_result',
            },
        ),
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weighted_marks', models.DecimalField(decimal_places=2, max_digits=7)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.assessmentcomponent')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.enrollment')),
            ],
            options={
                'db_table': 'student_marks',
            },
        ),
        migrations.CreateModel(
            name='CourseCart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.courseoffering')),
            ],
            options={
                'db_table': 'course_cart',
                'constraints': [models.UniqueConstraint(fields=('student', 'offering'), name='unique_course_cart_item')],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academics.enrollment')),
                ('is_counted_for_cpi', models.BooleanField()),
                ('grade_letter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.gradescale')),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student'], name='enrollment_student_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['offering'], name='enrollment_offering_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'offering'), name='unique_student_course_enrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('enrollment', 'date')},
        ),
        migrations.AddConstraint(
            model_name='coursegradescale',
            constraint=models.UniqueConstraint(fields=('offering', 'grade_letter'), name='unique_offering_grade_letter'),
        ),
        migrations.AddConstraint(
            model_name='coursegradescale',
            constraint=models.UniqueConstraint(fields=('offering', 'min_score'), name='unique_offering_min_score'),
        ),
        migrations.AlterUniqueTogether(
            name='prerequisite',
            unique_together={('course', 'prereq_course')},
        ),
        migrations.AlterUniqueTogether(
            name='semesterresult',
            unique_together={('student', 'academic_year', 'semester_no')},
        ),
        migrations.AddIndex(
            model_name='studentmarks',
            index=models.Index(fields=['enrollment'], name='studentmarks_enrollment_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentmarks',
            unique_together={('enrollment', 'component')},
        ),
    ]
