# Generated by Django 6.0 on 2026-04-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_schema_sync_post_restore'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('ATTENDANCE', 'Attendance Shortage'), ('GRADE', 'Low Grade')], max_length=50, null=True),
        ),
    ]
